
import { AptosParserRepo, getTypeTagFullname, StructTag, parseTypeTagOrThrow, u8, u64, u128, print, strToU8, u8str, DummyCache, ActualStringClass, sendPayloadTx, sendPayloadTxAndLog, getSimulationKeys } from "@foxdao/move-to-ts";
import { AptosAccount, AptosClient, HexString, Types } from "aptos";
import { Command } from "commander";
import { getProjectRepo } from "./";
import * as fs from "fs";
import * as yaml from "yaml";
import * as Hippo_tutorial from './hippo_tutorial';

export const readConfig = (program: Command) => {
  const {config, profile} = program.opts();
  const ymlContent = fs.readFileSync(config, {encoding: "utf-8"});
  const result = yaml.parse(ymlContent);
  //console.log(result);
  if (!result.profiles) {
    throw new Error("Expect a profiles to be present in yaml config");
  }
  if (!result.profiles[profile]) {
    throw new Error(`Expect a ${profile} profile to be present in yaml config`);
  }
  const url = result.profiles[profile].rest_url;
  const privateKeyStr = result.profiles[profile].private_key;
  if (!url) {
    throw new Error(`Expect rest_url to be present in ${profile} profile`);
  }
  if (!privateKeyStr) {
    throw new Error(`Expect private_key to be present in ${profile} profile`);
  }
  const privateKey = new HexString(privateKeyStr);
  const client = new AptosClient(result.profiles[profile].rest_url);
  const account = new AptosAccount(privateKey.toUint8Array());
  console.log(`Using address ${account.address().hex()}`);
  return {client, account};
}

const program = new Command();

program
  .name('yarn cli')
  .description('Move TS CLI generated by move-to-ts')
  .requiredOption('-c, --config <path>', 'path to your aptos config.yml (generated with "aptos init")')
  .option('-p, --profile <PROFILE>', 'aptos config profile to use', 'default')


const lend3_admin_add_pool = async (CoinType: string,initial_price: string,max_gas: string) => {
  const {client, account} = readConfig(program);
  const CoinType_ = parseTypeTagOrThrow(CoinType);
  const initial_price_ = u64(initial_price);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_admin_add_pool(initial_price_, [CoinType_]);
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:admin-add-pool")
  .description("Create a new lending pool (admin-only)")
  .argument('<TYPE_CoinType>')
  .argument('<initial_price>')
  .argument('[max_gas]', '', '10000')
  .action(lend3_admin_add_pool);


const lend3_admin_init = async (max_gas: string) => {
  const {client, account} = readConfig(program);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_admin_init();
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:admin-init")
  .description("Initialize protocol information (admin-only)")
  .argument('[max_gas]', '', '10000')
  .action(lend3_admin_init);


const lend3_admin_update_price = async (CoinType: string,price: string,max_gas: string) => {
  const {client, account} = readConfig(program);
  const CoinType_ = parseTypeTagOrThrow(CoinType);
  const price_ = u64(price);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_admin_update_price(price_, [CoinType_]);
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:admin-update-price")
  .description("Update price of a particular coin (admin-only)")
  .argument('<TYPE_CoinType>')
  .argument('<price>')
  .argument('[max_gas]', '', '10000')
  .action(lend3_admin_update_price);


const lend3_borrow = async (CoinType: string,amount: string,max_gas: string) => {
  const {client, account} = readConfig(program);
  const CoinType_ = parseTypeTagOrThrow(CoinType);
  const amount_ = u64(amount);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_borrow(amount_, [CoinType_]);
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:borrow")
  .description("Borrow from the CoinType pool. May fail if user exceeds borrow limit.")
  .argument('<TYPE_CoinType>')
  .argument('<amount>')
  .argument('[max_gas]', '', '10000')
  .action(lend3_borrow);


const lend3_create_fake_user1 = async (max_gas: string) => {
  const {client, account} = readConfig(program);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_create_fake_user1();
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:create-fake-user1")
  .description("")
  .argument('[max_gas]', '', '10000')
  .action(lend3_create_fake_user1);


const lend3_create_fake_user2 = async (max_gas: string) => {
  const {client, account} = readConfig(program);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_create_fake_user2();
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:create-fake-user2")
  .description("")
  .argument('[max_gas]', '', '10000')
  .action(lend3_create_fake_user2);


const lend3_create_fake_user3 = async (max_gas: string) => {
  const {client, account} = readConfig(program);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_create_fake_user3();
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:create-fake-user3")
  .description("")
  .argument('[max_gas]', '', '10000')
  .action(lend3_create_fake_user3);


const lend3_deposit = async (CoinType: string,amount: string,max_gas: string) => {
  const {client, account} = readConfig(program);
  const CoinType_ = parseTypeTagOrThrow(CoinType);
  const amount_ = u64(amount);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_deposit(amount_, [CoinType_]);
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:deposit")
  .description("Make a deposit into the CoinType pool. May create User if User does not already exist")
  .argument('<TYPE_CoinType>')
  .argument('<amount>')
  .argument('[max_gas]', '', '10000')
  .action(lend3_deposit);


const lend3_init_fake_pools = async (max_gas: string) => {
  const {client, account} = readConfig(program);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_init_fake_pools();
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:init-fake-pools")
  .description("")
  .argument('[max_gas]', '', '10000')
  .action(lend3_init_fake_pools);


const lend3_price_drop = async (max_gas: string) => {
  const {client, account} = readConfig(program);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_price_drop();
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:price-drop")
  .description("")
  .argument('[max_gas]', '', '10000')
  .action(lend3_price_drop);


const lend3_repay = async (CoinType: string,amount: string,max_gas: string) => {
  const {client, account} = readConfig(program);
  const CoinType_ = parseTypeTagOrThrow(CoinType);
  const amount_ = u64(amount);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_repay(amount_, [CoinType_]);
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:repay")
  .description("Repay existing debt in the CoinType pool. May fail if user does not have such debt.")
  .argument('<TYPE_CoinType>')
  .argument('<amount>')
  .argument('[max_gas]', '', '10000')
  .action(lend3_repay);


const lend3_withdraw = async (CoinType: string,amount: string,max_gas: string) => {
  const {client, account} = readConfig(program);
  const CoinType_ = parseTypeTagOrThrow(CoinType);
  const amount_ = u64(amount);
  const max_gas_ = parseInt(max_gas);
  const payload = Hippo_tutorial.Lend3.buildPayload_withdraw(amount_, [CoinType_]);
  await sendPayloadTxAndLog(client, account, payload,{maxGasAmount: max_gas_});
}

program
  .command("lend3:withdraw")
  .description("Withdraw from the CoinType pool. May fail if user exceeds borrow limit, or if he does not have enough deposit")
  .argument('<TYPE_CoinType>')
  .argument('<amount>')
  .argument('[max_gas]', '', '10000')
  .action(lend3_withdraw);


const lend3_get_all_users = async (max_gas: string) => {
  const {client, account} = readConfig(program);
  const repo = getProjectRepo();
  const value = await Hippo_tutorial.Lend3.query_get_all_users(client, getSimulationKeys(account), repo, [], {maxGasAmount: parseInt(max_gas)})
  print(value);
}

program
  .command("lend3:query-get-all-users")
  .argument('[max_gas]', '', '10000')
  .action(lend3_get_all_users)




program.parse();
